server {
    listen 3000;

    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        rewrite ^/([^/]+)$ /$1.html break;
        try_files $uri $uri/ /index.html;
    }

    location = /metrics {
        default_type text/plain;
        alias /usr/share/nginx/html/metrics;
    }
}
